palette = 0=#3C3C3C
palette = 1=#C9321A
palette = 2=#1F9E3A
palette = 3=#CE9314
palette = 4=#1F90E1
palette = 5=#A322A3
palette = 6=#1A39E9
palette = 7=#CFCFCF
palette = 8=#999999
palette = 9=#C9321A
palette = 10=#1F9E3A
palette = 11=#E3E922
palette = 12=#1A39E9
palette = 13=#A322A3
palette = 14=#1F9E3A
palette = 15=#CFCFCF
background = #EFEFEF
foreground = #212121
cursor-color = #1F88F1
cursor-text = #F9F9F9
selection-background = #CFCFCF
selection-foreground = #212121
split-divider-color = #A322A3
