local C = require("peafowl_colors.palettes")

--- @type { [string]: HiGroup }
return {
  Comment = { values = { fg = C.gray1 }, style = { italic = true } },
  SpecialComment = { link = "Comment" },
  Constant = { values = { fg = C.amber }, style = { bold = true } },
  String = { values = { fg = C.amber } },
  Character = { link = "String" },
  Number = { values = { fg = C.scarlet } },
  Float = { link = "Number" },
  Boolean = { values = { fg = C.amethyst }, style = { bold = true } },
  Identifier = { values = { fg = C.black }, style = { bold = true } },
  Function = { values = { fg = C.sapphire }, style = { bold = true } },
  Statement = { link = "String" },
  Conditional = { values = { fg = C.scarlet }, style = { bold = true } },
  Repeat = { values = { fg = C.emerald }, style = { bold = true } },
  Label = { link = "Identifier" },
  Operator = { values = { fg = C.blue } },
  Keyword = { values = { fg = C.emerald }, style = { bold = true } },
  Exception = { values = { fg = C.scarlet } },

  PreProc = { values = { fg = C.mastard }, style = { bold = true } },
  Include = { link = "PreProc" },
  Define = { values = { fg = C.amber }, style = { bold = true } },
  Macro = { link = "Define" },
  PreCondit = { link = "Define" },

  StorageClass = { values = { fg = C.sapphire } },
  Structure = { link = "StorageClass" },
  Special = { values = { fg = C.emerald }, style = { bold = true } },
  Type = { values = { fg = C.amber }, style = { bold = true } },
  Typedef = { link = "Type" },
  SpecialChar = { link = "Special" },
  Tag = { link = "Special" },
  Delimiter = { link = "Special" },
  Debug = { link = "Special" },
  Error = { values = { fg = C.scarlet }, style = { bold = true } },

  -- Underlined = { style = { underline = true } },
  -- Bold = { style = { bold = true } },
  -- Italic = { style = { italic = true } },

  Added = { values = { fg = C.green } },
  Changed = { values = { fg = C.blue } },
  diffAdded = { values = { fg = C.green } },
  diffRemoved = { values = { fg = C.red } },
  diffChanged = { values = { fg = C.amber } },
  diffOldFile = { values = { fg = C.red } },
  diffNewFile = { values = { fg = C.green } },
  diffFile = { values = { fg = C.black } },
  diffLine = { values = { fg = C.gray1 } },
  diffIndexLine = { values = { fg = C.gray0 } },
  DiffAdd = { link = "diffAdded" },
  DiffChange = { link = "diffChanged" },
  DiffDelete = { link = "diffRemoved" },
  DiffText = { values = { fg = C.black } },

  healthError = { values = { fg = C.red } },
  healthSuccess = { values = { fg = C.green } },
  healthWarning = { values = { fg = C.yellow } },

  GlyphPalette1 = { values = { fg = C.emerald } },
  GlyphPalette2 = { values = { fg = C.amber } },
  GlyphPalette3 = { values = { fg = C.amethyst } },
  GlyphPalette4 = { values = { fg = C.sapphire } },
  GlyphPalette5 = { values = { fg = C.mastard } },
  GlyphPalette6 = { values = { fg = C.scarlet } },
  GlyphPalette7 = { values = { fg = C.green } },
  GlyphPalette8 = { values = { fg = C.blue } },
  GlyphPalette9 = { values = { fg = C.red } },

  rainbow1 = { values = { fg = C.scarlet } },
  rainbow2 = { values = { fg = C.amber } },
  rainbow3 = { values = { fg = C.yellow } },
  rainbow4 = { values = { fg = C.green } },
  rainbow5 = { values = { fg = C.blue } },
  rainbow6 = { values = { fg = C.amethyst } },

  csvCol0 = { values = { fg = C.emerald } },
  csvCol1 = { values = { fg = C.amber } },
  csvCol2 = { values = { fg = C.amethyst } },
  csvCol3 = { values = { fg = C.sapphire } },
  csvCol4 = { values = { fg = C.mastard } },
  csvCol5 = { values = { fg = C.scarlet } },
  csvCol6 = { values = { fg = C.green } },
  csvCol7 = { values = { fg = C.blue } },

  markdownHeadingDelimiter = { values = { fg = C.gray0 } },
  markdownCode = { values = { fg = C.amber } },
  markdownCodeBlock = { values = { fg = C.amethyst } },
  markdownLinkText = { values = { fg = C.blue }, style = { underline = true } },
  markdownH1 = { values = { fg = C.emerald }, style = { bold = true } },
  markdownH2 = { values = { fg = C.amber }, style = { bold = true } },
  markdownH3 = { values = { fg = C.amethyst }, style = { bold = true } },
  markdownH4 = { values = { fg = C.sapphire }, style = { bold = true } },
  markdownH5 = { values = { fg = C.mastard }, style = { bold = true } },
  markdownH6 = { values = { fg = C.scarlet }, style = { bold = true } },
}
